import React, { useState, useEffect } from 'react';
import styles from '../../pages/AdminPage.module.css';
import { Plus, Edit, Trash2, Users, Check, X } from 'lucide-react';
import { api } from '../../services/api';

export const EmployeesTab = () => {
    const [employees, setEmployees] = useState([]);
    const [loading, setLoading] = useState(true);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingId, setEditingId] = useState(null);

    // Form State
    const [formData, setFormData] = useState({
        name: '',
        email: '',
        role: 'editor',
        department: '',
        active: true,
        color: '#3b82f6' // Default color
    });

    const fetchEmployees = async () => {
        try {
            setLoading(true);
            const data = await api.getEmployees();
            setEmployees(data);
        } catch (error) {
            console.error("Failed to fetch employees", error);
            alert("Nepodarilo sa načítať zamestnancov.");
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchEmployees();
    }, []);

    const handleOpenModal = (employee = null) => {
        if (employee) {
            setEditingId(employee.id);
            setFormData({
                name: employee.name,
                email: employee.email,
                role: employee.role,
                department: employee.department,
                active: employee.active,
                color: employee.color || '#3b82f6'
            });
        } else {
            setEditingId(null);
            setFormData({
                name: '',
                email: '',
                role: 'editor',
                department: '',
                active: true,
                color: '#3b82f6'
            });
        }
        setIsModalOpen(true);
    };

    const handleSave = async (e) => {
        e.preventDefault();
        try {
            if (editingId) {
                await api.updateEmployee(editingId, formData);
            } else {
                await api.createEmployee({
                    ...formData,
                    // ID generated by json-server or manually if needed, usually json-server handles IDs but we can send one if we want specific format
                    // id: `emp-${Date.now()}`, 
                    joinedDate: new Date().toISOString().split('T')[0]
                });
            }
            await fetchEmployees();
            setIsModalOpen(false);
        } catch (error) {
            console.error("Save failed", error);
            alert("Uloženie zlyhalo.");
        }
    };

    const handleDelete = async (id) => {
        if (window.confirm('Naozaj chcete odstrániť tohto zamestnanca?')) {
            try {
                await api.deleteEmployee(id);
                await fetchEmployees();
            } catch (error) {
                console.error("Delete failed", error);
                alert("Vymazanie zlyhalo.");
            }
        }
    };

    const handleToggleStatus = async (employee) => {
        try {
            await api.updateEmployee(employee.id, { active: !employee.active });
            await fetchEmployees();
        } catch (error) {
            console.error("Status update failed", error);
            alert("Zmena statusu zlyhala.");
        }
    };

    return (
        <div className={styles.tableContainer}>
            <div style={{ padding: '1rem', textAlign: 'right', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <h3 style={{ margin: 0, paddingLeft: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--text-muted)' }}>
                    <Users size={20} /> Zoznam zamestnancov
                </h3>
                <button className="btn btn-primary" onClick={() => handleOpenModal()}>
                    <Plus size={16} /> Pridať zamestnanca
                </button>
            </div>

            <table className={styles.table}>
                <thead>
                    <tr>
                        <th>Meno</th>
                        <th>Email</th>
                        <th>Rola</th>
                        <th>Oddelenie</th>
                        <th>Status</th>
                        <th>Akcie</th>
                    </tr>
                </thead>
                <tbody>
                    {employees.map(emp => (
                        <tr key={emp.id}>
                            <td style={{ fontWeight: 600 }}>{emp.name}</td>
                            <td style={{ color: '#64748b' }}>{emp.email}</td>
                            <td>
                                <span style={{
                                    padding: '0.25rem 0.75rem',
                                    borderRadius: '99px',
                                    fontSize: '0.8rem',
                                    fontWeight: 600,
                                    background: emp.role === 'admin' ? '#e0e7ff' : '#f1f5f9',
                                    color: emp.role === 'admin' ? '#4338ca' : '#475569'
                                }}>
                                    {emp.role.toUpperCase()}
                                </span>
                            </td>
                            <td>{emp.department}</td>
                            <td>
                                <button
                                    onClick={() => handleToggleStatus(emp)}
                                    style={{
                                        border: 'none',
                                        background: 'transparent',
                                        cursor: 'pointer',
                                        color: emp.active ? '#16a34a' : '#dc2626',
                                        display: 'flex',
                                        alignItems: 'center',
                                        gap: '0.25rem',
                                        fontWeight: 600,
                                        fontSize: '0.85rem'
                                    }}
                                >
                                    {emp.active ? <><Check size={14} /> Aktívny</> : <><X size={14} /> Neaktívny</>}
                                </button>
                            </td>
                            <td>
                                <div style={{ display: 'flex', gap: '0.5rem' }}>
                                    <button className={styles.actionBtn} onClick={() => handleOpenModal(emp)}>
                                        <Edit size={16} />
                                    </button>
                                    <button className={styles.actionBtn} onClick={() => handleDelete(emp.id)} style={{ color: '#dc2626', borderColor: '#fee2e2', background: '#fef2f2' }}>
                                        <Trash2 size={16} />
                                    </button>
                                </div>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>

            {/* Modal */}
            {isModalOpen && (
                <div className={styles.modalOverlay}>
                    <div className={styles.modalContent}>
                        <div className={styles.modalHeader}>
                            <h2>{editingId ? 'Upraviť zamestnanca' : 'Nový zamestnanec'}</h2>
                            <button className={styles.closeBtn} onClick={() => setIsModalOpen(false)}>
                                <X size={20} />
                            </button>
                        </div>
                        <form onSubmit={handleSave} className={styles.formGrid}>
                            <div className={styles.formGroup}>
                                <label>Meno</label>
                                <input
                                    required
                                    value={formData.name}
                                    onChange={e => setFormData({ ...formData, name: e.target.value })}
                                    placeholder="Janko Hraško"
                                />
                            </div>
                            <div className={styles.formGroup}>
                                <label>Email</label>
                                <input
                                    required
                                    type="email"
                                    value={formData.email}
                                    onChange={e => setFormData({ ...formData, email: e.target.value })}
                                    placeholder="email@firma.sk"
                                />
                            </div>
                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                                <div className={styles.formGroup}>
                                    <label>Rola</label>
                                    <select
                                        value={formData.role}
                                        onChange={e => setFormData({ ...formData, role: e.target.value })}
                                    >
                                        <option value="admin">Admin</option>
                                        <option value="manager">Manažér</option>
                                        <option value="editor">Editor</option>
                                        <option value="viewer">Pozorovateľ</option>
                                    </select>
                                </div>
                                <div className={styles.formGroup}>
                                    <label>Oddelenie</label>
                                    <input
                                        value={formData.department}
                                        onChange={e => setFormData({ ...formData, department: e.target.value })}
                                        placeholder="IT, Sklad..."
                                    />
                                </div>
                            </div>

                            <div className={styles.modalActions}>
                                <button type="button" className="btn btn-outline" onClick={() => setIsModalOpen(false)}>Zrušiť</button>
                                <button type="submit" className="btn btn-primary">Uložiť</button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};
